language: erlang
matrix:
  include:
    - os: linux
      sudo: required
      otp_release: R15B03
    - os: linux
      sudo: required
      otp_release: R16B03-1
    - os: linux
      sudo: required
      otp_release: 17.5
    - os: linux
      sudo: required
      otp_release: 18.3
    - os: linux
      sudo: required
      otp_release: 19.2
    - os: osx
      sudo: required
      language: generic
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  ## should eventually use a tap that has previous erlang versions here
  ## as this only uses the latest erlang available via brew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install erlang; fi
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script: "./rebar3 update && ./rebar3 ct"
branches:
  only:
    - master
addons:
    hostname: travis.dev 
notifications:
  email:
    - core@erlware.org
  irc:
    channels:
      - "irc.freenode.org#erlware"
    use_notice: true
    skip_join: true
